name: Linux Packaging CI
on:
    # Build whenever a file that affects the packaging build is changed by a push
    push:
        paths:
            - .github/workflows/linux-packaging.yml
            - build.sh
            - gui/tasks/**
            - gui/package.json
            - gui/gulpfile.js
            - mullvad-management-interface/proto/**
    # Build if requested manually from the Actions tab
    workflow_dispatch:
jobs:
    build-linux-packages-x86_64:
        strategy:
            matrix:
                os: [ubuntu-latest]
                rust: [stable]

        runs-on: ${{ matrix.os }}
        steps:

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Checkout submodules
              run: git submodule update --init --depth=1

            - name: Install Rust
              uses: ATiltedTree/setup-rust@v1.0.4
              with:
                  rust-version: ${{ matrix.rust }}

            - name: Install Go
              uses: actions/setup-go@v2.1.3
              with:
                  go-version: 1.16

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: '12'

            - name: Update NPM
              run: npm i -g npm

            - name: Install build dependencies
              run: sudo apt-get install libdbus-1-dev rpm dpkg-dev

            - name: Install and cache dependencies
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: gui
                  install-command: npm ci

            - name: Build
              run: ./build.sh --dev-build

            - name: 'Upload deb package'
              uses: actions/upload-artifact@v2
              with:
                name: linux-x86_64-deb
                path: dist/Mullvad*.deb

            - name: 'Upload rpm package'
              uses: actions/upload-artifact@v2
              with:
                name: linux-x86_64-rpm
                path: dist/Mullvad*.rpm
            
            - name: 'Bundle built proto files'
              run: mkdir -p miproto && cp gui/src/main/management_interface/*.ts gui/build/src/main/management_interface/*.js miproto/

            - name: 'Upload proto files'
              uses: actions/upload-artifact@v2
              with:
                name: linux-mi-proto-build
                path: miproto

    build-linux-packages-arm64:
      needs: build-linux-packages-x86_64
      if: ${{ github.event_name == 'push' }}
      strategy:
          matrix:
              rust: [stable]

      runs-on: [self-hosted, linux, ARM64]
      steps:

          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Checkout submodules
            run: git submodule update --init --depth=1

          - name: Install Rust
            uses: nikitalita/setup-rust@v1.0.5
            with:
                rust-version: ${{ matrix.rust }}

          - name: Install Go
            uses: actions/setup-go@v2.1.3
            with:
                go-version: 1.16

          - name: Setup Node.js environment
            uses: actions/setup-node@v2.1.5
            with:
                node-version: '12'

          - name: Update NPM
            run: npm i -g npm

          # - name: Install build dependencies
          #   run: sudo apt-get install libdbus-1-dev rpm dpkg-dev gcc ruby ruby-dev rubygems build-essential protobuf-compiler

          # - name: Install system fpm
          #   run: sudo gem install --no-document fpm:1.12.0

          - name: Install and cache dependencies
            uses: bahmutov/npm-install@v1
            with:
                working-directory: gui
                install-command: npm ci

          - name: Download proto files from previous x86_64 job
            uses: actions/download-artifact@v2
            with:
              name: linux-mi-proto-build

          - name: Build
            run: MANAGEMENT_INTERFACE_PROTO_BUILD_DIR=${PWD}/miproto USE_SYSTEM_FPM=1 ./build.sh --dev-build

          - name: 'Upload deb package'
            uses: actions/upload-artifact@v2
            with:
              name: linux-arm64-deb
              path: dist/Mullvad*.deb

          - name: 'Upload rpm package'
            uses: actions/upload-artifact@v2
            with:
              name: linux-arm64-rpm
              path: dist/Mullvad*.rpm